/**
 * Bill briefings and person/organization dossiers (E4). Cached in app.briefing and marked stale when
 * a new document touches the entity (markStaleBriefings, run by the alert pipeline after each batch).
 *
 * Every line is a fact with at least one cited document; the plain-language summary is generated by
 * lib/ai/claude.ts under the citation validator (facts-only fallback). The bill "Indicators" section
 * lists factual signals only and is never labeled or phrased as a prediction.
 */
import type { Db } from '@/lib/db/types'
import { classifyStatus } from '@/lib/alerts/events'
import { generateCitedNarrative, type NarrativeModel } from '@/lib/ai/claude'
import type { Fact } from '@/lib/ai/citations'
import type { DocModel, SourceDoc } from '@/lib/render/model'

export interface BriefingLine { text: string; documentIds: string[] }
export interface BriefingSection { key: string; title: string; lines: BriefingLine[]; note?: string }
export interface BriefingContent {
  kind: 'bill' | 'person' | 'org'
  entity: { id: string; name: string; kind: string }
  summary: { source: 'model' | 'facts_only'; sentences: BriefingLine[]; model: string | null }
  sections: BriefingSection[]
  generated_at: string
}

export interface BriefingRow { id: string; entity_id: string; kind: string; generated_at: string; content: BriefingContent; cites: string[]; stale: boolean }

const TWO_CYCLES_YEARS = 4
const money = (n: number) => `$${Math.round(n).toLocaleString('en-US')}`
const plural = (n: number, s: string) => `${n} ${s}${n === 1 ? '' : 's'}`

function allCites(c: BriefingContent): string[] {
  const ids = new Set<string>()
  for (const s of c.summary.sentences) s.documentIds.forEach(d => ids.add(d))
  for (const sec of c.sections) for (const l of sec.lines) l.documentIds.forEach(d => ids.add(d))
  return [...ids]
}

// ------------------------------------------------------------------------------------------------ bill briefing

export async function buildBillBriefing(db: Db, billId: string, opts: { model?: NarrativeModel | null; now?: Date } = {}): Promise<BriefingContent> {
  const now = opts.now ?? new Date()
  const bill = await db.one<{ id: string; name: string; kind: string; identifiers: Record<string, string>; attributes: Record<string, unknown> }>(
    `select id, name, kind, identifiers, attributes from entity where id = $1 and kind = 'bill'`, [billId])
  if (!bill) throw new Error('Bill not found')
  const a = bill.attributes
  const measureDoc = bill.identifiers.measure
    ? await db.one<{ id: string; raw: { statusHistory?: Array<{ date: string | null; text: string }>; description?: string; title?: string } }>(
      `select id, raw from document where source = 'capitol_measures' and source_record_id = $1`, [bill.identifiers.measure])
    : null
  const md = measureDoc?.id
  const history = measureDoc?.raw.statusHistory ?? []
  const cite = (id: string | null | undefined) => (id ? [id] : [])

  // Status and next deadline
  const status: BriefingLine[] = []
  const current = (a.current_status as string | undefined) ?? history.at(-1)?.text
  if (current && md) status.push({ text: `Current status: ${current}`, documentIds: [md] })
  if (a.current_referral && md) status.push({ text: `Current referral: ${a.current_referral}`, documentIds: [md] })
  if (current && md) {
    const c = classifyStatus(current)
    if (c.hearingAt && c.hearingAt > now && c.type !== 'bill.hearing_canceled') {
      const hstStr = (d: Date) => new Date(d.getTime() - 36e6).toISOString().replace('T', ' ').slice(0, 16) + ' HST'
      status.push({ text: `Next deadline: testimony for the ${c.committees.join('/') || 'committee'} hearing at ${hstStr(c.hearingAt)} is due by ${hstStr(new Date(c.hearingAt.getTime() - 864e5))}`, documentIds: [md] })
    }
  }
  const amendments = history.filter(h => /\b(HD|SD|CD)\s?\d\b/.test(h.text)).slice(-2)

  // Committees of referral, members, and their votes so far on this bill
  const referral = String(a.current_referral ?? '').split(/[,/]/).map(s => s.trim().toUpperCase()).filter(s => /^[A-Z]{2,4}$/.test(s))
  const votes = await db.many<{ committee: string | null; person: string; role: string | null; doc_id: string; date: string | null }>(
    `select e.attributes->>'committee' committee, coalesce(p.name, e.from_name_raw) person, e.role, e.document_id doc_id, e.start_date::text date
       from edge e left join entity p on p.id = e.from_id where e.type = 'voted_on' and e.to_id = $1
      order by e.start_date nulls last, e.role, coalesce(p.name, e.from_name_raw)`, [billId])
  const members = referral.length ? await db.many<{ committee: string; person: string; role: string | null; doc_id: string }>(
    `select coalesce(c.identifiers->>'committee_code', c.attributes->>'code', c.name) committee, coalesce(p.name, e.from_name_raw) person, e.role, e.document_id doc_id
       from edge e join entity c on c.id = e.to_id left join entity p on p.id = e.from_id
      where e.type = 'member_of' and (e.end_date is null or e.end_date >= current_date)
        and (upper(regexp_replace(coalesce(c.identifiers->>'committee_code', c.attributes->>'code', ''), '^\\d{4}:[HS]:', '')) = any($1::text[]))
      order by case e.role when 'chair' then 0 when 'vice chair' then 1 else 2 end, coalesce(p.name, e.from_name_raw)`, [referral]) : []
  const committeeLines: BriefingLine[] = []
  for (const code of referral) {
    const ms = members.filter(m => m.committee.replace(/^\d{4}:[HS]:/, '').toUpperCase() === code)
    const vs = votes.filter(v => (v.committee ?? '').toUpperCase().includes(code))
    if (ms.length) committeeLines.push({ text: `${code} members: ${ms.map(m => `${m.person}${m.role && m.role !== 'member' ? ` (${m.role})` : ''}`).join(', ')}`, documentIds: [...new Set(ms.map(m => m.doc_id))].slice(0, 5) })
    if (vs.length) {
      const tally = new Map<string, string[]>()
      for (const v of vs) tally.set(v.role ?? 'recorded', [...(tally.get(v.role ?? 'recorded') ?? []), v.person])
      committeeLines.push({ text: `${code} vote: ${[...tally].map(([r, ps]) => `${r} — ${ps.join(', ')}`).join('; ')}`, documentIds: [...new Set(vs.map(v => v.doc_id))] })
    }
    if (!ms.length && !vs.length && md) committeeLines.push({ text: `${code}: referred; no membership roster or votes on file yet`, documentIds: [md] })
  }
  const floor = votes.filter(v => !v.committee)
  if (floor.length) {
    const t = new Map<string, number>()
    for (const v of floor) t.set(v.role ?? 'recorded', (t.get(v.role ?? 'recorded') ?? 0) + 1)
    committeeLines.push({ text: `Floor votes recorded: ${[...t].map(([r, n]) => `${n} ${r}`).join(', ')}`, documentIds: [...new Set(floor.map(v => v.doc_id))] })
  }

  // Testimony by organization, grouped by position
  const testimony = await db.many<{ who: string; who_id: string | null; kind: string | null; role: string | null; doc_id: string }>(
    `select coalesce(f.name, e.from_name_raw) who, e.from_id who_id, f.kind, e.role, e.document_id doc_id
       from edge e left join entity f on f.id = e.from_id where e.type = 'testified_on' and e.to_id = $1
      order by coalesce(f.name, e.from_name_raw), e.document_id`, [billId])
  const testimonyLines: BriefingLine[] = []
  for (const pos of ['support', 'oppose', 'comment']) {
    const list = testimony.filter(t => (t.role ?? 'comment') === pos)
    if (!list.length) continue
    const orgs = [...new Set(list.filter(t => t.kind === 'org').map(t => t.who))]
    testimonyLines.push({
      text: `${pos === 'support' ? 'In support' : pos === 'oppose' ? 'In opposition' : 'Comments'}: ${plural(list.length, 'testifier')}${orgs.length ? `, including ${orgs.slice(0, 12).join(', ')}${orgs.length > 12 ? ` and ${orgs.length - 12} more organizations` : ''}` : ''}`,
      documentIds: [...new Set(list.map(t => t.doc_id))].slice(0, 12),
    })
  }

  // Sponsors
  const sponsors = await db.many<{ id: string | null; name: string; role: string | null; doc_id: string }>(
    `select e.from_id id, coalesce(p.name, e.from_name_raw) name, e.role, e.document_id doc_id
       from edge e left join entity p on p.id = e.from_id where e.type = 'sponsored' and e.to_id = $1 order by (e.attributes->>'order')::int nulls last`, [billId])

  // Money: last two cycles, from testifying orgs, their officers, and clients lobbying on this bill → sponsors and referral-committee members.
  const lobbying = await db.many<{ who: string; who_id: string | null; role: string | null; doc_id: string }>(
    `select coalesce(f.name, e.from_name_raw) who, e.from_id who_id, e.role, e.document_id doc_id
       from edge e left join entity f on f.id = e.from_id where e.type = 'lobbied_on' and e.to_id = $1
      order by coalesce(f.name, e.from_name_raw)`, [billId])
  const donorOrgs = [...new Set([...testimony.filter(t => t.kind === 'org' && t.who_id).map(t => t.who_id!), ...lobbying.filter(l => l.who_id).map(l => l.who_id!)])]
  const officers = donorOrgs.length ? await db.many<{ id: string }>(
    `select distinct from_id id from edge where type in ('officer_of','director_of') and to_id = any($1::uuid[]) and from_id is not null`, [donorOrgs]) : []
  const donors = [...new Set([...donorOrgs, ...officers.map(o => o.id)])]
  const recipientIds = [...new Set([...sponsors.filter(s => s.id).map(s => s.id!),
    ...(referral.length ? (await db.many<{ id: string }>(
      `select distinct e.from_id id from edge e join entity c on c.id = e.to_id where e.type = 'member_of' and e.from_id is not null
          and upper(regexp_replace(coalesce(c.identifiers->>'committee_code', c.attributes->>'code', ''), '^\\d{4}:[HS]:', '')) = any($1::text[])`, [referral])).map(r => r.id) : [])])]
  const contributions = donors.length && recipientIds.length ? await db.many<{ donor: string; recipient: string; total: string; n: number; docs: string[] }>(
    `select coalesce(f.name, e.from_name_raw) donor, coalesce(t.name, e.to_name_raw) recipient, sum(e.amount)::text total, count(*)::int n, array_agg(distinct e.document_id) docs
       from edge e left join entity f on f.id = e.from_id left join entity t on t.id = e.to_id
      where e.type = 'contributed_to' and e.from_id = any($1::uuid[]) and e.to_id = any($2::uuid[])
        and coalesce(e.start_date, current_date) >= (current_date - make_interval(years => ${TWO_CYCLES_YEARS}))
      group by 1, 2 order by sum(e.amount) desc nulls last, 1, 2 limit 25`, [donors, recipientIds]) : []
  const moneyLines: BriefingLine[] = contributions.map(c => ({
    text: `${c.donor} → ${c.recipient}: ${money(Number(c.total ?? 0))} in ${plural(c.n, 'contribution')}`, documentIds: c.docs.slice(0, 8),
  }))

  const lobbyingLines: BriefingLine[] = lobbying.map(l => ({ text: `${l.who}${l.role ? ` (${l.role})` : ''} reported lobbying on this bill`, documentIds: [l.doc_id] }))

  // Indicators — factual signals only.
  const indicators: BriefingLine[] = []
  const sup = testimony.filter(t => t.role === 'support').length, opp = testimony.filter(t => t.role === 'oppose').length, com = testimony.filter(t => (t.role ?? 'comment') === 'comment').length
  if (testimony.length) indicators.push({ text: `Testimony balance: ${sup} support, ${opp} oppose, ${com} comments`, documentIds: [...new Set(testimony.map(t => t.doc_id))].slice(0, 12) })
  if (sponsors.length) {
    const intro = sponsors.filter(s => s.role === 'introducer').length
    indicators.push({ text: `Sponsors: ${plural(sponsors.length, 'legislator')} (${intro} introducer, ${sponsors.length - intro} co-introducers)`, documentIds: [...new Set(sponsors.map(s => s.doc_id))] })
  }
  if (votes.length) {
    const byRole = new Map<string, number>()
    for (const v of votes) byRole.set(v.role ?? 'recorded', (byRole.get(v.role ?? 'recorded') ?? 0) + 1)
    indicators.push({ text: `Committee and floor votes so far: ${[...byRole].map(([r, n]) => `${n} ${r}`).join(', ')}`, documentIds: [...new Set(votes.map(v => v.doc_id))] })
  }

  const sections: BriefingSection[] = [
    { key: 'status', title: 'Status and next deadline', lines: status, note: 'Session-calendar deadlines (decking, crossover) appear once the Legislature’s session calendar is ingested.' },
    { key: 'drafts', title: 'Changes between drafts', lines: amendments.map(h => ({ text: `${h.date ?? ''} ${h.text}`.trim(), documentIds: cite(md) })) },
    { key: 'committees', title: 'Committees of referral', lines: committeeLines },
    { key: 'sponsors', title: 'Sponsors', lines: sponsors.map(s => ({ text: `${s.name}${s.role ? ` (${s.role})` : ''}`, documentIds: [s.doc_id] })) },
    { key: 'testimony', title: 'Testimony by position', lines: testimonyLines },
    { key: 'money', title: `Contributions in the last two election cycles`, lines: moneyLines,
      note: 'From testifying organizations, their officers and directors, and organizations lobbying on this bill, to the sponsors and to members of the referral committees.' },
    { key: 'lobbying', title: 'Lobbying filings naming this bill', lines: lobbyingLines },
    { key: 'indicators', title: 'Indicators', lines: indicators, note: 'Factual signals recorded so far. This section does not predict an outcome.' },
  ]

  const facts: Fact[] = []
  if (md) facts.push({ documentId: md, text: `${bill.name}: ${a.title ?? measureDoc?.raw.title ?? ''}. ${a.description ?? measureDoc?.raw.description ?? ''}`.trim(), kind: 'measure' })
  for (const s of sections.filter(s => ['status', 'drafts', 'indicators'].includes(s.key))) for (const l of s.lines) facts.push({ documentId: l.documentIds[0], text: l.text, kind: s.title })
  const narrative = await generateCitedNarrative({
    task: `Write a plain-language summary (2 to 4 sentences) of what ${bill.name} does as currently drafted, then what changed in the latest amendment if the facts say so.`,
    facts, maxSentences: 4, rules: ['Explain in plain language; do not quote legal boilerplate.', 'Never predict whether the bill will pass.'],
  }, opts.model === undefined ? undefined : opts.model)

  return {
    kind: 'bill', entity: { id: bill.id, name: bill.name, kind: 'bill' },
    summary: { source: narrative.source, sentences: narrative.sentences, model: narrative.model },
    sections, generated_at: now.toISOString(),
  }
}

// ------------------------------------------------------------------------------------------------ dossiers

const ROLE_TYPES = ['officer_of', 'director_of', 'member_of', 'appointed_to', 'employed_by', 'confirmed_by']

export async function buildDossier(db: Db, entityId: string, opts: { model?: NarrativeModel | null; watchIds?: string[]; now?: Date } = {}): Promise<BriefingContent> {
  const now = opts.now ?? new Date()
  const e = await db.one<{ id: string; name: string; kind: 'person' | 'org' }>(`select id, name, kind from entity where id = $1 and kind in ('person','org')`, [entityId])
  if (!e) throw new Error('Person or organization not found')
  const edges = await db.many<{ id: string; type: string; from_id: string | null; to_id: string | null; a: string; b: string; role: string | null; amount: string | null; start_date: string | null; end_date: string | null; doc_id: string }>(
    `select e.id, e.type, e.from_id, e.to_id, coalesce(f.name, e.from_name_raw, '') a, coalesce(t.name, e.to_name_raw, d.title, '') b, e.role, e.amount::text amount,
            e.start_date::text start_date, e.end_date::text end_date, e.document_id doc_id
       from edge e join document d on d.id = e.document_id left join entity f on f.id = e.from_id left join entity t on t.id = e.to_id
      where (e.from_id = $1 or e.to_id = $1) and e.match_status = 'matched'
      order by e.start_date desc nulls last limit 2000`, [entityId])
  const out = (t: string[]) => edges.filter(x => t.includes(x.type) && x.from_id === entityId)
  const inn = (t: string[]) => edges.filter(x => t.includes(x.type) && x.to_id === entityId)
  const period = (x: { start_date: string | null; end_date: string | null }) => x.start_date ? ` (${x.start_date}${x.end_date ? ` to ${x.end_date}` : ''})` : ''

  const roles = [...out(ROLE_TYPES), ...inn(['employed_by', 'officer_of', 'director_of', 'member_of'])].slice(0, 40).map(x => ({
    text: x.from_id === entityId ? `${x.type.replace(/_/g, ' ')} ${x.b}${x.role ? ` — ${x.role}` : ''}${period(x)}` : `${x.a} ${x.type.replace(/_/g, ' ')} ${e.name}${x.role ? ` — ${x.role}` : ''}${period(x)}`,
    documentIds: [x.doc_id],
  }))
  const moneyAgg = (list: typeof edges, other: 'a' | 'b') => {
    const m = new Map<string, { total: number; n: number; docs: Set<string> }>()
    for (const x of list) {
      const k = x[other]
      const v = m.get(k) ?? { total: 0, n: 0, docs: new Set<string>() }
      v.total += Number(x.amount ?? 0); v.n++; v.docs.add(x.doc_id)
      m.set(k, v)
    }
    return [...m].sort((p, q) => q[1].total - p[1].total).slice(0, 15)
  }
  const moneyIn = moneyAgg(inn(['contributed_to', 'loaned_to']), 'a').map(([k, v]) => ({ text: `From ${k}: ${money(v.total)} in ${plural(v.n, 'record')}`, documentIds: [...v.docs].slice(0, 8) }))
  const moneyOut = moneyAgg(out(['contributed_to', 'spent_with', 'loaned_to']), 'b').map(([k, v]) => ({ text: `To ${k}: ${money(v.total)} in ${plural(v.n, 'record')}`, documentIds: [...v.docs].slice(0, 8) }))
  const lobbying = [...out(['lobbied_for', 'lobbied_on']), ...inn(['lobbied_for'])].slice(0, 30).map(x => ({
    text: x.from_id === entityId ? `${x.type === 'lobbied_on' ? 'Lobbied on' : 'Registered to lobby for'} ${x.b}${x.role ? ` (${x.role})` : ''}${period(x)}` : `${x.a} registered to lobby for ${e.name}${period(x)}`,
    documentIds: [x.doc_id],
  }))
  const contracts = [...out(['awarded_contract', 'awarded_grant']), ...inn(['awarded_contract', 'awarded_grant'])].slice(0, 30).map(x => ({
    text: `${x.a} ${x.type.replace(/_/g, ' ')} ${x.b}${x.amount ? `: ${money(Number(x.amount))}` : ''}${period(x)}`, documentIds: [x.doc_id],
  }))
  const property = out(['owns', 'leases']).slice(0, 30).map(x => ({ text: `${x.type === 'owns' ? 'Owns' : 'Leases'} ${x.b}${period(x)}`, documentIds: [x.doc_id] }))
  const testimony = out(['testified_on']).slice(0, 30).map(x => ({ text: `Testified${x.role ? ` (${x.role})` : ''} on ${x.b}${period(x)}`, documentIds: [x.doc_id] }))
  const recent = await db.many<{ id: string; title: string | null; source: string; doc_date: string | null }>(
    `select d.id, d.title, d.source, d.doc_date::text doc_date from document d
      where d.id in (select document_id from edge where from_id = $1 or to_id = $1)
      order by d.doc_date desc nulls last, d.fetched_at desc limit 10`, [entityId])
  const recentLines = recent.map(d => ({ text: `${d.doc_date ?? 'Undated'} — ${d.title ?? `${d.source} record`}`, documentIds: [d.id] }))

  const paths: BriefingLine[] = []
  for (const target of (opts.watchIds ?? []).filter(id => id !== entityId).slice(0, 25)) {
    const p = await connectionPath(db, entityId, target)
    if (p) paths.push(p)
    if (paths.length >= 10) break
  }

  const sections: BriefingSection[] = [
    { key: 'roles', title: 'Roles and appointments', lines: roles },
    { key: 'money_in', title: 'Money in', lines: moneyIn },
    { key: 'money_out', title: 'Money out', lines: moneyOut },
    { key: 'lobbying', title: 'Lobbying relationships', lines: lobbying },
    { key: 'contracts', title: 'Contracts and grants', lines: contracts },
    { key: 'property', title: 'Property', lines: property },
    { key: 'testimony', title: 'Testimony', lines: testimony },
    { key: 'recent', title: 'Recent documents', lines: recentLines },
    { key: 'paths', title: 'Connections to watched entities', lines: paths, note: 'Shortest chains of recorded relationships (up to three steps). A connection is not evidence of coordination.' },
  ]
  const facts: Fact[] = sections.filter(s => s.key !== 'paths').flatMap(s => s.lines.slice(0, 8).map(l => ({ documentId: l.documentIds[0], text: `${s.title}: ${l.text}` })))
  const narrative = await generateCitedNarrative({
    task: `Write a neutral 2 to 4 sentence overview of ${e.name}'s documented roles, money, and lobbying relationships.`, facts, maxSentences: 4,
    rules: ['Do not infer motives, relationships, or wrongdoing beyond the facts.'],
  }, opts.model === undefined ? undefined : opts.model)
  return { kind: e.kind, entity: { id: e.id, name: e.name, kind: e.kind }, summary: { source: narrative.source, sentences: narrative.sentences, model: narrative.model }, sections, generated_at: now.toISOString() }
}

/** Shortest chain (≤ 3 hops) of observed, matched edges between two entities; every hop cites its document. */
export async function connectionPath(db: Db, fromId: string, toId: string, maxHops = 3): Promise<BriefingLine | null> {
  type Hop = { prev: string; edge: string; doc: string; type: string }
  const prev = new Map<string, Hop | null>([[fromId, null]])
  let frontier = [fromId]
  for (let depth = 0; depth < maxHops && frontier.length && !prev.has(toId); depth++) {
    const rows = await db.many<{ a: string; b: string; id: string; doc: string; type: string }>(
      `select from_id a, to_id b, id, document_id doc, type from edge
        where match_status = 'matched' and from_id is not null and to_id is not null and type <> 'mentioned_in'
          and (from_id = any($1::uuid[]) or to_id = any($1::uuid[])) limit 20000`, [frontier])
    const next: string[] = []
    const inFrontier = new Set(frontier)
    for (const r of rows) {
      for (const [here, there] of [[r.a, r.b], [r.b, r.a]] as const) {
        if (!inFrontier.has(here) || prev.has(there)) continue
        prev.set(there, { prev: here, edge: r.id, doc: r.doc, type: r.type })
        next.push(there)
      }
    }
    frontier = next
  }
  if (!prev.has(toId)) return null
  const chain: Array<{ from: string; to: string; hop: Hop }> = []
  let cur = toId
  while (cur !== fromId) { const h = prev.get(cur)!; chain.unshift({ from: h.prev, to: cur, hop: h }); cur = h.prev }
  const ids = [...new Set(chain.flatMap(c => [c.from, c.to]))]
  const names = new Map((await db.many<{ id: string; name: string }>(`select id, name from entity where id = any($1::uuid[])`, [ids])).map(r => [r.id, r.name]))
  return {
    text: chain.map((c, i) => `${i === 0 ? names.get(c.from) : ''} —${c.hop.type.replace(/_/g, ' ')}— ${names.get(c.to)}`).join(' '),
    documentIds: chain.map(c => c.hop.doc),
  }
}

// ------------------------------------------------------------------------------------------------ cache

export async function getOrBuildBriefing(db: Db, entityId: string, opts: { model?: NarrativeModel | null; watchIds?: string[]; force?: boolean } = {}): Promise<BriefingRow> {
  const e = await db.one<{ kind: string }>(`select kind from entity where id = $1`, [entityId])
  if (!e || !['bill', 'person', 'org'].includes(e.kind)) throw new Error('Briefings are available for bills, people, and organizations')
  const cached = await db.one<BriefingRow>(`select * from app.briefing where entity_id = $1 and kind = $2`, [entityId, e.kind])
  // Dossier connection paths depend on the viewer's watchlist, so dossiers with paths are rebuilt per request.
  if (cached && !cached.stale && !opts.force && !(e.kind !== 'bill' && opts.watchIds?.length)) return cached
  const content = e.kind === 'bill' ? await buildBillBriefing(db, entityId, opts) : await buildDossier(db, entityId, opts)
  if (e.kind !== 'bill' && opts.watchIds?.length) {
    return { id: cached?.id ?? '', entity_id: entityId, kind: e.kind, generated_at: content.generated_at, content, cites: allCites(content), stale: false }
  }
  return (await db.one<BriefingRow>(
    `insert into app.briefing(entity_id, kind, content, cites, stale, generated_at) values ($1, $2, $3, $4::uuid[], false, now())
     on conflict (entity_id, kind) do update set content = excluded.content, cites = excluded.cites, stale = false, generated_at = now()
     returning *`, [entityId, e.kind, JSON.stringify(content), allCites(content)]))!
}

/** Mark cached briefings stale when documents or edges touching their entity arrived since `since`. */
export async function markStaleBriefings(db: Db, since: Date): Promise<number> {
  const r = await db.query(
    `update app.briefing b set stale = true
      where not b.stale and (
        exists (select 1 from edge e where (e.from_id = b.entity_id or e.to_id = b.entity_id) and e.created_at > $1)
        or exists (select 1 from entity x join document d on d.source = 'capitol_measures' and d.source_record_id = x.identifiers->>'measure'
                    where x.id = b.entity_id and d.fetched_at > $1))`, [since.toISOString()])
  return r.rowCount
}

export async function briefingDocModel(db: Db, row: BriefingRow): Promise<DocModel> {
  const c = row.content
  const sources = row.cites.length ? await db.many<SourceDoc>(`select id, title, source, doc_date::text doc_date, url from document where id = any($1::uuid[])`, [row.cites]) : []
  return {
    title: c.kind === 'bill' ? `Bill briefing: ${c.entity.name}` : `Dossier: ${c.entity.name}`,
    subtitle: c.summary.source === 'facts_only' ? 'Compiled directly from records' : undefined,
    sections: [
      { heading: 'Summary', blocks: [{ type: 'p', runs: c.summary.sentences.map(s => ({ text: `${s.text} `, cites: s.documentIds })) }] },
      ...c.sections.filter(s => s.lines.length).map(s => ({
        heading: s.title,
        blocks: [...(s.note ? [{ type: 'note' as const, text: s.note }] : []), ...s.lines.map(l => ({ type: 'li' as const, runs: [{ text: l.text, cites: l.documentIds }] }))],
      })),
    ],
    sources, generatedAt: c.generated_at,
  }
}
