/**
 * Client reports (E3): facts → cited narrative → draft → edit → approve → send / download.
 *
 * Facts come only from the database (status history of watched bills, votes, testimony, activity
 * on watched entities, upcoming hearings), each tied to a document id. The narrative is generated by
 * lib/ai/claude.ts under the citation validator; if the model is unavailable or fails validation
 * twice, the report ships facts-only. Nothing is emailed until a team member approves the report
 * (enforced here and by the app.guard_report_status trigger).
 */
import type { Db } from '@/lib/db/types'
import { classifyStatus } from '@/lib/alerts/events'
import { generateCitedNarrative, type NarrativeModel } from '@/lib/ai/claude'
import type { Fact } from '@/lib/ai/citations'
import { getEmailTransport, type EmailTransport } from '@/lib/email/resend'
import { renderEmail } from '@/lib/email/template'
import { renderPdf } from '@/lib/render/pdf'
import { renderDocx } from '@/lib/render/docx'
import type { Block, DocModel, Run, SourceDoc } from '@/lib/render/model'
import { getTeamEntitlements, EntitlementError } from '@/lib/entitlements'
import { getRole, type TeamRow } from '@/lib/teams'
import { SITE_URL } from '@/lib/site'

export interface ReportItem { text: string; documentIds: string[]; date?: string | null }
export interface ReportSection { key: string; title: string; items: ReportItem[] }
export type RichBlock = { type: 'p' | 'li'; runs: Array<{ text: string; bold?: boolean; italic?: boolean; cites?: string[] }> }

export interface ReportContent {
  client: { id: string; name: string }
  period: { start: string; end: string }
  sections: ReportSection[]
  narrative: { source: 'model' | 'facts_only' | 'edited'; blocks: RichBlock[]; model: string | null; errors: string[] }
  generated_at: string
}

export interface ReportRow {
  id: string; team_id: string; client_id: string; period_start: string; period_end: string
  status: 'draft' | 'approved' | 'sent'; content: ReportContent; cited_document_ids: string[]; narrative_source: string
  pdf_key: string | null; docx_key: string | null; recipients: string[]; created_by: string | null
  approved_by: string | null; approved_at: string | null; sent_at: string | null; created_at: string; updated_at: string
}

export class ReportError extends Error { constructor(message: string, public status = 400) { super(message) } }

const ISO = /^\d{4}-\d{2}-\d{2}$/

async function requireMember(db: Db, teamId: string, userId: string) {
  if (!(await getRole(db, teamId, userId))) throw new ReportError('Not a member of this team', 403)
  const e = await getTeamEntitlements(db, teamId)
  if (!e.reports) throw new EntitlementError('reports', e.tier)
}

// ------------------------------------------------------------------------------------------------ facts

export async function assembleClientFacts(db: Db, clientId: string, start: string, end: string, now = new Date()): Promise<{ client: { id: string; name: string; entity_id: string | null; team_id: string }; sections: ReportSection[] }> {
  const client = await db.one<{ id: string; name: string; entity_id: string | null; team_id: string }>(`select id, name, entity_id, team_id from app.client where id = $1`, [clientId])
  if (!client) throw new ReportError('Client not found', 404)
  const watched = await db.many<{ id: string; kind: string; name: string; measure: string | null; current_status: string | null }>(
    `select distinct e.id, e.kind, e.name, e.identifiers->>'measure' measure, e.attributes->>'current_status' current_status
       from app.watchlist w join app.watchlist_item i on i.watchlist_id = w.id join entity e on e.id = i.entity_id
      where w.client_id = $1`, [clientId])
  const bills = watched.filter(w => w.kind === 'bill')
  const billIds = bills.map(b => b.id)
  const others = watched.filter(w => w.kind !== 'bill').map(w => w.id)
  if (client.entity_id) others.push(client.entity_id)

  const status = billIds.length ? await db.many<{ bill: string; doc_id: string; date: string; text: string }>(
    `select e.name bill, d.id doc_id, h->>'date' date, h->>'text' text
       from entity e join document d on d.source = 'capitol_measures' and d.source_record_id = e.identifiers->>'measure'
       cross join lateral jsonb_array_elements(case when jsonb_typeof(d.raw->'statusHistory') = 'array' then d.raw->'statusHistory' else '[]'::jsonb end) h
      where e.id = any($1::uuid[]) and (h->>'date') ~ '^\\d{4}-\\d{2}-\\d{2}$'
        and (case when (h->>'date') ~ '^\\d{4}-\\d{2}-\\d{2}$' then (h->>'date')::date end) between $2::date and $3::date
      order by 3, 1`, [billIds, start, end]) : []

  const statusItems: ReportItem[] = [], hearingItems: ReportItem[] = [], draftItems: ReportItem[] = [], outcomeItems: ReportItem[] = []
  for (const s of status) {
    const item = { text: `${s.bill}: ${s.text.replace(/\s+/g, ' ').trim()}`, documentIds: [s.doc_id], date: s.date }
    const t = classifyStatus(s.text).type
    if (/\bAct\s+\d+|vetoed|became law|enrolled to governor|intent to veto|failed|died/i.test(s.text)) outcomeItems.push(item)
    else if (t.startsWith('bill.hearing')) hearingItems.push(item)
    else if (t === 'bill.new_draft' || t === 'bill.committee_report') draftItems.push(item)
    else statusItems.push(item)
  }

  const votes = billIds.length ? await db.many<{ bill: string; doc_id: string; date: string | null; committee: string | null; tally: Record<string, number> }>(
    `select b.name bill, e.document_id doc_id, min(coalesce(e.start_date, d.doc_date))::text date, max(e.attributes->>'committee') committee,
            jsonb_object_agg(coalesce(e.role, 'recorded'), n) tally
       from (select document_id, to_id, role, count(*)::int n, min(start_date) start_date, jsonb_build_object('committee', max(attributes->>'committee')) attributes
               from edge where type = 'voted_on' and to_id = any($1::uuid[]) group by document_id, to_id, role) e
       join entity b on b.id = e.to_id join document d on d.id = e.document_id
      where coalesce(e.start_date, d.doc_date, d.fetched_at::date) between $2::date and $3::date
      group by b.name, e.document_id order by 3, 1, 2`, [billIds, start, end]) : []
  const voteItems: ReportItem[] = votes.map(v => ({
    text: `${v.bill}: vote recorded${v.committee ? ` in ${v.committee}` : ''} — ${Object.entries(v.tally).map(([k, n]) => `${n} ${k}`).join(', ')}`,
    documentIds: [v.doc_id], date: v.date,
  }))

  const testimony = billIds.length ? await db.many<{ who: string; bill: string; role: string | null; doc_id: string; date: string | null; named: boolean }>(
    `select coalesce(f.name, e.from_name_raw) who, b.name bill, e.role, e.document_id doc_id, coalesce(e.start_date, d.doc_date)::text date,
            (e.from_id is not distinct from $4::uuid or coalesce(f.name, e.from_name_raw) ilike $5 or coalesce(e.attributes->>'organization', '') ilike $5) named
       from edge e join entity b on b.id = e.to_id join document d on d.id = e.document_id left join entity f on f.id = e.from_id
      where e.type = 'testified_on' and e.to_id = any($1::uuid[])
        and coalesce(e.start_date, d.doc_date, d.fetched_at::date) between $2::date and $3::date
      order by named desc, 5, 1, 4 limit 200`, [billIds, start, end, client.entity_id, `%${client.name.replace(/[%_]/g, '')}%`]) : []
  const testimonyItems: ReportItem[] = testimony.filter(t => t.named).map(t => ({ text: `${t.who} testified${t.role ? ` (${t.role})` : ''} on ${t.bill}`, documentIds: [t.doc_id], date: t.date }))
  const balance = new Map<string, { support: number; oppose: number; comment: number; docs: Set<string> }>()
  for (const t of testimony) {
    const b = balance.get(t.bill) ?? { support: 0, oppose: 0, comment: 0, docs: new Set<string>() }
    const k = (t.role ?? 'comment') as 'support' | 'oppose' | 'comment'
    if (k in b) b[k]++
    b.docs.add(t.doc_id)
    balance.set(t.bill, b)
  }
  for (const [bill, b] of balance) {
    testimonyItems.push({ text: `${bill}: testimony filed — ${b.support} in support, ${b.oppose} in opposition, ${b.comment} with comments`, documentIds: [...b.docs].slice(0, 10) })
  }

  const activity = others.length ? await db.many<{ a: string; type: string; b: string; amount: string | null; doc_id: string; date: string | null }>(
    `select coalesce(f.name, e.from_name_raw) a, e.type, coalesce(t.name, e.to_name_raw, d.title, '') b, e.amount::text amount, e.document_id doc_id,
            coalesce(e.start_date, d.doc_date, e.created_at::date)::text date
       from edge e join document d on d.id = e.document_id left join entity f on f.id = e.from_id left join entity t on t.id = e.to_id
      where (e.from_id = any($1::uuid[]) or e.to_id = any($1::uuid[])) and e.match_status = 'matched'
        and coalesce(e.start_date, d.doc_date, e.created_at::date) between $2::date and $3::date
      order by 6 desc, 1, 2, 3 limit 50`, [others, start, end]) : []
  const activityItems: ReportItem[] = activity.map(a => ({
    text: `${a.a} ${a.type.replace(/_/g, ' ')} ${a.b}${a.amount ? ` ($${Number(a.amount).toLocaleString('en-US')})` : ''}`.trim(), documentIds: [a.doc_id], date: a.date,
  }))

  const upcoming: ReportItem[] = []
  const measureDocs = bills.filter(b => b.measure).length ? await db.many<{ measure: string; id: string }>(
    `select source_record_id measure, id from document where source = 'capitol_measures' and source_record_id = any($1::text[])`, [bills.map(b => b.measure).filter(Boolean)]) : []
  const docByMeasure = new Map(measureDocs.map(d => [d.measure, d.id]))
  for (const b of bills) {
    if (!b.current_status) continue
    const c = classifyStatus(b.current_status)
    if (!c.hearingAt || c.hearingAt < now || c.type === 'bill.hearing_canceled') continue
    const docId = b.measure ? docByMeasure.get(b.measure) : undefined
    if (!docId) continue
    const deadline = new Date(c.hearingAt.getTime() - 24 * 3600_000)
    upcoming.push({ text: `${b.name}: hearing ${hst(c.hearingAt)}; testimony due by ${hst(deadline)}${c.committees.length ? ` (${c.committees.join(', ')})` : ''}`, documentIds: [docId], date: c.hearingAt.toISOString().slice(0, 10) })
  }

  const sections: ReportSection[] = [
    { key: 'status', title: 'Bill status changes', items: statusItems },
    { key: 'hearings', title: 'Hearings', items: hearingItems },
    { key: 'votes', title: 'Votes', items: voteItems },
    { key: 'drafts', title: 'Drafts and committee reports', items: draftItems },
    { key: 'outcomes', title: 'Outcomes', items: outcomeItems },
    { key: 'testimony', title: 'Testimony', items: testimonyItems },
    { key: 'activity', title: 'Related activity', items: activityItems },
    { key: 'upcoming', title: 'Upcoming hearings and deadlines', items: upcoming },
  ]
  return { client, sections }
}

const hst = (d: Date) => new Date(d.getTime() - 10 * 3600_000).toISOString().replace('T', ' ').slice(0, 16) + ' HST'

function factsFromSections(sections: ReportSection[]): Fact[] {
  return sections.flatMap(s => s.items.map(i => ({ documentId: i.documentIds[0], text: i.text, date: i.date ?? null, kind: s.title })))
    .filter(f => f.documentId)
}

export function narrativeBlocks(sentences: Array<{ text: string; documentIds: string[] }>): RichBlock[] {
  if (!sentences.length) return [{ type: 'p', runs: [{ text: 'No activity on this client’s watched items in this period.' }] }]
  return [{ type: 'p', runs: sentences.map(s => ({ text: `${s.text} `, cites: s.documentIds })) }]
}

export function citedIds(content: ReportContent): string[] {
  const ids = new Set<string>()
  for (const s of content.sections) for (const i of s.items) i.documentIds.forEach(d => ids.add(d))
  for (const b of content.narrative.blocks) for (const r of b.runs) r.cites?.forEach(d => ids.add(d))
  return [...ids]
}

// ------------------------------------------------------------------------------------------------ workflow

export async function generateReportDraft(db: Db, args: { teamId: string; clientId: string; start: string; end: string; userId: string | null; model?: NarrativeModel | null; now?: Date }): Promise<ReportRow> {
  if (!ISO.test(args.start) || !ISO.test(args.end) || args.end < args.start) throw new ReportError('Invalid period')
  if (args.userId) await requireMember(db, args.teamId, args.userId)
  else { const e = await getTeamEntitlements(db, args.teamId); if (!e.reports) throw new EntitlementError('reports', e.tier) }
  const { client, sections } = await assembleClientFacts(db, args.clientId, args.start, args.end, args.now)
  if (client.team_id !== args.teamId) throw new ReportError('Client not found', 404)
  const facts = factsFromSections(sections)
  const narrative = await generateCitedNarrative({
    task: `Write a short narrative summary (3 to 6 sentences) of the period ${args.start} to ${args.end} for the client ${client.name}, covering the most significant bill actions, votes, testimony, and upcoming deadlines.`,
    facts, maxSentences: 6,
    rules: ['Do not characterize outcomes as good or bad for the client.', 'Refer to bills by their number as given in the facts.'],
  }, args.model === undefined ? undefined : args.model)
  const content: ReportContent = {
    client: { id: client.id, name: client.name }, period: { start: args.start, end: args.end }, sections,
    narrative: { source: narrative.source, blocks: narrativeBlocks(narrative.sentences), model: narrative.model, errors: narrative.errors },
    generated_at: new Date().toISOString(),
  }
  const recipients = (await db.one<{ report_recipients: string[] }>(`select report_recipients from app.client where id = $1`, [client.id]))!.report_recipients
  const row = await db.one<ReportRow>(
    `insert into app.report(team_id, client_id, period_start, period_end, status, content, cited_document_ids, narrative_source, recipients, created_by)
     values ($1, $2, $3, $4, 'draft', $5, $6::uuid[], $7, $8, $9) returning *`,
    [args.teamId, client.id, args.start, args.end, JSON.stringify(content), citedIds(content), narrative.source, recipients, args.userId])
  await db.query(`insert into app.usage_event(team_id, user_id, kind) values ($1, $2, 'report.generated')`, [args.teamId, args.userId])
  return row!
}

export async function getReport(db: Db, teamId: string, reportId: string): Promise<ReportRow | null> {
  return db.one<ReportRow>(`select * from app.report where id = $1 and team_id = $2`, [reportId, teamId])
}

const cleanRuns = (runs: RichBlock['runs'], allowed: Set<string>) => runs
  .map(r => ({ text: String(r.text ?? '').slice(0, 5000), bold: !!r.bold || undefined, italic: !!r.italic || undefined, cites: (r.cites ?? []).filter(c => allowed.has(c)) }))
  .map(r => (r.cites.length ? r : { ...r, cites: undefined }))
  .filter(r => r.text.length || r.cites)

/** Save browser edits. Editing an approved report returns it to draft (it must be approved again). */
export async function updateReportDraft(db: Db, args: { teamId: string; reportId: string; userId: string; blocks: RichBlock[]; recipients?: string[] }): Promise<ReportRow> {
  await requireMember(db, args.teamId, args.userId)
  const report = await getReport(db, args.teamId, args.reportId)
  if (!report) throw new ReportError('Report not found', 404)
  if (report.status === 'sent') throw new ReportError('A sent report cannot be edited', 409)
  // Citations may only point at documents already in the report's fact base.
  const allowed = new Set(report.content.sections.flatMap(s => s.items.flatMap(i => i.documentIds)))
  const blocks: RichBlock[] = (args.blocks ?? []).slice(0, 200)
    .map(b => ({ type: b.type === 'li' ? 'li' as const : 'p' as const, runs: cleanRuns(b.runs ?? [], allowed) }))
    .filter(b => b.runs.length)
  const content: ReportContent = { ...report.content, narrative: { ...report.content.narrative, source: 'edited', blocks } }
  const recipients = args.recipients ? args.recipients.map(r => r.trim().toLowerCase()).filter(r => /^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(r)).slice(0, 50) : report.recipients
  return (await db.one<ReportRow>(
    `update app.report set content = $3, cited_document_ids = $4::uuid[], narrative_source = 'edited', recipients = $5, status = 'draft', pdf_key = null, docx_key = null
      where id = $1 and team_id = $2 returning *`,
    [args.reportId, args.teamId, JSON.stringify(content), citedIds(content), recipients]))!
}

/** Uncited sentences in an edited narrative (shown as warnings before approval). */
export function uncitedSentences(blocks: RichBlock[]): string[] {
  const out: string[] = []
  for (const b of blocks) {
    let buf = ''
    for (const r of b.runs) {
      buf += r.text
      if (r.cites?.length) buf = ''
      else if (/[.!?]\s*$/.test(buf.trim()) && buf.trim().length > 3) { out.push(buf.trim()); buf = '' }
    }
    if (buf.trim().length > 3) out.push(buf.trim())
  }
  return out
}

async function sourcesFor(db: Db, ids: string[]): Promise<SourceDoc[]> {
  if (!ids.length) return []
  return db.many<SourceDoc>(`select id, title, source, doc_date::text doc_date, url from document where id = any($1::uuid[])`, [ids])
}

async function teamLogo(db: Db, team: TeamRow): Promise<DocModel['logo']> {
  const key = team.letterhead_key ?? team.logo_key
  if (!key) return null
  const f = await db.one<{ bytes: Uint8Array; content_type: string }>(`select bytes, content_type from app.stored_file where key = $1`, [key])
  if (!f) return null
  return { bytes: new Uint8Array(f.bytes), type: f.content_type === 'image/png' ? 'png' : 'jpg' }
}

export async function reportDocModel(db: Db, report: ReportRow): Promise<DocModel> {
  const team = (await db.one<TeamRow>(`select * from app.team where id = $1`, [report.team_id]))!
  const c = report.content
  const itemRun = (i: ReportItem): Run => ({ text: i.date ? `${i.date} — ${i.text}` : i.text, cites: i.documentIds })
  const sections = [
    { heading: 'Summary', blocks: c.narrative.blocks.map(b => ({ type: b.type, runs: b.runs })) as Block[] },
    ...c.sections.filter(s => s.items.length).map(s => ({ heading: s.title, blocks: s.items.map(i => ({ type: 'li' as const, runs: [itemRun(i)] })) })),
  ]
  if (c.narrative.source === 'facts_only') sections[0].blocks.push({ type: 'note', text: 'Summary compiled directly from the records below.' })
  return {
    title: `${c.client.name}: legislative report`, subtitle: `${c.period.start} to ${c.period.end}`,
    preparedFor: c.client.name, preparedBy: team.is_personal ? undefined : team.name,
    logo: await teamLogo(db, team), sections, sources: await sourcesFor(db, citedIds(c)), generatedAt: c.generated_at,
  }
}

async function storeFile(db: Db, teamId: string, key: string, contentType: string, bytes: Uint8Array) {
  await db.query(`insert into app.stored_file(key, team_id, content_type, bytes) values ($1, $2, $3, $4)
                  on conflict (key) do update set bytes = excluded.bytes, content_type = excluded.content_type, created_at = now()`,
    [key, teamId, contentType, Buffer.from(bytes)])
}

export async function renderReportFiles(db: Db, report: ReportRow): Promise<{ pdf: Uint8Array; docx: Uint8Array }> {
  const model = await reportDocModel(db, report)
  return { pdf: await renderPdf(model), docx: await renderDocx(model) }
}

/** Explicit approval by a team member: freezes the content and stores the rendered PDF and DOCX. */
export async function approveReport(db: Db, args: { teamId: string; reportId: string; userId: string }): Promise<ReportRow> {
  await requireMember(db, args.teamId, args.userId)
  const report = await getReport(db, args.teamId, args.reportId)
  if (!report) throw new ReportError('Report not found', 404)
  if (report.status === 'sent') throw new ReportError('Report already sent', 409)
  const files = await renderReportFiles(db, report)
  const base = `reports/${report.team_id}/${report.id}`
  await storeFile(db, report.team_id, `${base}.pdf`, 'application/pdf', files.pdf)
  await storeFile(db, report.team_id, `${base}.docx`, 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', files.docx)
  return (await db.one<ReportRow>(
    `update app.report set status = 'approved', approved_by = $3, approved_at = now(), pdf_key = $4, docx_key = $5
      where id = $1 and team_id = $2 and status in ('draft','approved') returning *`,
    [args.reportId, args.teamId, args.userId, `${base}.pdf`, `${base}.docx`]))!
}

export async function getReportFile(db: Db, teamId: string, reportId: string, format: 'pdf' | 'docx'): Promise<{ bytes: Uint8Array; contentType: string; filename: string } | null> {
  const report = await getReport(db, teamId, reportId)
  if (!report) return null
  const key = format === 'pdf' ? report.pdf_key : report.docx_key
  const name = `${report.content.client.name.replace(/[^A-Za-z0-9]+/g, '-')}-${report.period_start}-to-${report.period_end}.${format}`
  if (key) {
    const f = await db.one<{ bytes: Uint8Array; content_type: string }>(`select bytes, content_type from app.stored_file where key = $1 and team_id = $2`, [key, teamId])
    if (f) return { bytes: new Uint8Array(f.bytes), contentType: f.content_type, filename: name }
  }
  // Drafts render on demand (preview); approved reports always come from the stored files.
  const files = await renderReportFiles(db, report)
  return { bytes: format === 'pdf' ? files.pdf : files.docx, filename: `DRAFT-${name}`,
    contentType: format === 'pdf' ? 'application/pdf' : 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' }
}

/** Email an approved report to the client's recipients from the team's sender name. */
export async function sendReport(db: Db, args: { teamId: string; reportId: string; userId: string; transport?: EmailTransport }): Promise<ReportRow> {
  await requireMember(db, args.teamId, args.userId)
  const report = await getReport(db, args.teamId, args.reportId)
  if (!report) throw new ReportError('Report not found', 404)
  if (report.status !== 'approved' || !report.approved_by) throw new ReportError('Approve the report before sending it', 409)
  if (!report.recipients.length) throw new ReportError('Add at least one recipient', 400)
  const team = (await db.one<TeamRow>(`select * from app.team where id = $1`, [args.teamId]))!
  const pdf = await getReportFile(db, args.teamId, args.reportId, 'pdf')
  const docx = await getReportFile(db, args.teamId, args.reportId, 'docx')
  const c = report.content
  const { html, text } = renderEmail({
    title: `${c.client.name}: ${c.period.start} to ${c.period.end}`, brand: team.sender_name ?? team.name,
    intro: 'The report for this period is attached as PDF and Word files.',
    blocks: [{ lines: c.narrative.blocks.flatMap(b => b.runs).filter(r => r.text.trim()).map(r => ({ text: r.text.trim() })) }],
    footer: [{ text: `Prepared by ${team.name} with HOKU Insider`, href: SITE_URL }],
  })
  const [res] = await (args.transport ?? getEmailTransport()).send([{
    to: report.recipients, subject: `${c.client.name} — report for ${c.period.start} to ${c.period.end}`, html, text,
    fromName: team.sender_name ?? team.name, tags: { kind: 'client_report' },
    attachments: [
      { filename: pdf!.filename, content: Buffer.from(pdf!.bytes), contentType: pdf!.contentType },
      { filename: docx!.filename, content: Buffer.from(docx!.bytes), contentType: docx!.contentType },
    ],
  }])
  if (!res.ok) throw new ReportError(`Email failed: ${res.error ?? 'unknown error'}`, 502)
  await db.query(`insert into app.usage_event(team_id, user_id, kind) values ($1, $2, 'report.sent')`, [args.teamId, args.userId])
  return (await db.one<ReportRow>(`update app.report set status = 'sent', sent_at = now() where id = $1 and status = 'approved' returning *`, [args.reportId]))!
}

// ------------------------------------------------------------------------------------------------ weekly auto-draft

/** Previous Monday–Sunday week in Honolulu time. */
export function lastWeek(now: Date): { start: string; end: string } {
  const local = new Date(now.getTime() - 10 * 3600_000)
  const dow = (local.getUTCDay() + 6) % 7 // Monday = 0
  const thisMonday = new Date(Date.UTC(local.getUTCFullYear(), local.getUTCMonth(), local.getUTCDate() - dow))
  const start = new Date(thisMonday.getTime() - 7 * 86_400_000)
  const end = new Date(thisMonday.getTime() - 86_400_000)
  return { start: start.toISOString().slice(0, 10), end: end.toISOString().slice(0, 10) }
}

/** Draft (never send) last week's report for every client with auto_draft on; notify owners/admins. */
export async function runWeeklyAutoDrafts(db: Db, opts: { now?: Date; transport?: EmailTransport; model?: NarrativeModel | null } = {}): Promise<number> {
  const now = opts.now ?? new Date()
  const { start, end } = lastWeek(now)
  const clients = await db.many<{ id: string; team_id: string; name: string }>(
    `select c.id, c.team_id, c.name from app.client c
      where c.auto_draft and c.report_cadence = 'weekly' and (app.team_features(c.team_id)).reports
        and not exists (select 1 from app.report r where r.client_id = c.id and r.period_start = $1 and r.period_end = $2)`, [start, end])
  let n = 0
  for (const c of clients) {
    const r = await generateReportDraft(db, { teamId: c.team_id, clientId: c.id, start, end, userId: null, model: opts.model, now })
    n++
    const admins = await db.many<{ email: string }>(
      `select email from app.team_member where team_id = $1 and role in ('owner','admin') and joined_at is not null and removed_at is null and email is not null`, [c.team_id])
    if (!admins.length) continue
    const { html, text } = renderEmail({
      title: `Draft report ready: ${c.name}`, intro: `A draft report for ${start} to ${end} is ready for review. It will not be sent until someone on your team approves it.`,
      blocks: [{ lines: [{ text: 'Review the draft', href: `${SITE_URL}/workspace/reports/${r.id}` }] }],
      footer: [{ text: 'HOKU Insider', href: SITE_URL }],
    })
    await (opts.transport ?? getEmailTransport()).send([{ to: admins.map(a => a.email), subject: `[HOKU Insider] Draft report ready: ${c.name}`, html, text, tags: { kind: 'report_draft_notice' } }])
  }
  return n
}
